# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Desafio Técnico - Digital Grid

**Candidato:** Shayane Ferreira Silva Pereira

## Objetivo

Este notebook apresenta a solução das questões Q0 a Q5 do desafio técnico para a vaga de Pesquisador em Ciência de Dados.
"""



"""# Q0 — Carregamento e preparação dos dados

Nesta etapa são importadas as bibliotecas, carregadas as bases de dados e realizada uma análise inicial para verificar a estrutura dos arquivos.
"""

# Informações gerais das bases

print("=== CONSUMER ===")
print("Dimensão:", consumer.shape)
print("\nColunas:")
print(consumer.columns.tolist())

print("\nValores nulos:")
print(consumer.isnull().sum())

print("\nDuplicatas:", consumer.duplicated().sum())

print("\n")

print("=== POWER ===")
print("Dimensão:", power.shape)

print("\nColunas:")
print(power.columns.tolist())

print("\nValores nulos:")
print(power.isnull().sum())

print("\nDuplicatas:", power.duplicated().sum())

# Cópias para não alterar as bases originais
consumer_clean = consumer.copy()
power_clean = power.copy()

# Remover registros duplicados
consumer_clean = consumer_clean.drop_duplicates()
power_clean = power_clean.drop_duplicates()

# Converter datas
consumer_clean["Geração Mensal Referência Month"] = pd.to_datetime(
    consumer_clean["Geração Mensal Referência Month"]
)

power_clean["Geração Mensal Referência Month"] = pd.to_datetime(
    power_clean["Geração Mensal Referência Month"],
    errors="coerce"
)

# Remover registros com data inválida
power_clean = power_clean.dropna(
    subset=["Geração Mensal Referência Month"]
)

print("Consumer limpo:", consumer_clean.shape)
print("Power limpo:", power_clean.shape)

## Conclusão da Q0

Foi realizada uma análise inicial da qualidade dos dados.

As principais verificações incluíram:

- Identificação de valores nulos;
- Identificação de registros duplicados;
- Conversão das colunas de data para o tipo `datetime`;
- Remoção de registros inválidos da base da usina.

Essas etapas garantem uma base consistente para as análises seguintes.



"""# Q1 — Cobertura e Rateio

Nesta etapa foi implementada a lógica para integrar o consumo das unidades consumidoras com a geração mensal da usina, permitindo avaliar a disponibilidade de energia para compensação.
"""

# Renomear colunas para facilitar a manipulação

consumer_q1 = consumer_clean.rename(columns={
    "Geração Mensal Referência Month": "mes",
    "Unidade Consumidora (UC) Número de Instalação": "uc",
    "Conta Consumo (kWh)": "consumo",
    "Conta Saldo Acumulado (kWh)": "saldo"
})

power_q1 = power_clean.rename(columns={
    "Geração Mensal Referência Month": "mes",
    "Geração Mensal SUM Energia Gerada (kWh)": "geracao"
})

consumer_q1.head()

validacao = (
    dados.groupby("mes")["percentual_rateio"]
    .sum()
    .reset_index()
)

validacao.head()

# Q1 — Cobertura e rateio (versão final)

import numpy as np
import pandas as pd

# Nomes simplificados
mes_col = "Geração Mensal Referência Month"
uc_col = "Unidade Consumidora (UC) Número de Instalação"
consumo_col = "Conta Consumo (kWh)"
saldo_col = "Conta Saldo Acumulado (kWh)"

# O rateio usa o último mês faturado disponível: junho/2026
mes_rateio = pd.Timestamp("2026-06-01")

q1 = consumer_clean[
    consumer_clean[mes_col] == mes_rateio
].copy()

# Tratar duplicidade estrutural de UC no mesmo mês
# Consumo é somado e o saldo é mantido pelo maior valor registrado
q1 = (
    q1.groupby([mes_col, uc_col], as_index=False)
      .agg({
          consumo_col: "sum",
          saldo_col: "max"
      })
)

# Parâmetros definidos no enunciado
q1["opf"] = 1.0
q1["d"] = 0.0

# Ec, Cr e ECA
q1["ec"] = q1[consumo_col]
q1["cr"] = q1[saldo_col]
q1["eca"] = q1["ec"] * q1["opf"]

# Cobertura: necessidade real de crédito
q1["co"] = np.maximum(
    q1["eca"] - (q1["cr"] + q1["d"]),
    0
)

# Percentual de rateio
soma_co = q1["co"].sum()

if soma_co > 0:
    q1["p"] = q1["co"] / soma_co
else:
    q1["p"] = 0.0

resultado_q1 = q1[
    [uc_col, "eca", "cr", "co", "p"]
].rename(columns={uc_col: "uc"})

print("Número de UCs:", len(resultado_q1))
print("Soma de Co:", round(soma_co, 4))
print("Soma de P:", round(resultado_q1["p"].sum(), 10))

resultado_q1.sort_values("p", ascending=False).head(10)



"""## Interpretação da Q1

O consumo aparente foi calculado por `ECA = Ec × OpF`, utilizando `OpF = 1`. A cobertura representa a necessidade real de novos créditos e foi calculada por `Co = max(ECA − (Cr + D), 0)`, com `D = 0`.

O percentual de rateio foi obtido pela divisão da cobertura de cada UC pela cobertura total da carteira. A soma de `P` igual a 1 confirma que 100% do rateio foi distribuído, mas não prova, isoladamente, que os dados de entrada ou as regras de limpeza estão corretos.

Caso `ΣCo = 0`, ocorre uma divisão por zero e `P` fica matematicamente indefinido. Em produção, o rateio deve ser interrompido, `P` deve receber zero para todas as UCs e o evento deve ser registrado em log para auditoria.
"""

import duckdb

con = duckdb.connect()

con.register("consumer", consumer_clean)

query = """
WITH base AS (
    SELECT
        "Unidade Consumidora (UC) Número de Instalação" AS uc,
        "Conta Consumo (kWh)" AS ec,
        "Conta Saldo Acumulado (kWh)" AS cr,
        1.0 AS opf,
        0.0 AS d
    FROM consumer
    WHERE "Geração Mensal Referência Month" = DATE '2026-06-01'
),

calc AS (
    SELECT
        uc,
        ec*opf AS eca,
        cr,
        GREATEST(ec*opf-(cr+d),0) AS co
    FROM base
)

SELECT
    uc,
    eca,
    cr,
    co,
    CASE
        WHEN SUM(co) OVER() = 0 THEN 0
        ELSE co/SUM(co) OVER()
    END AS p
FROM calc
ORDER BY p DESC;
"""

resultado_sql = con.execute(query).df()

resultado_sql.head()

print(consumer.columns.tolist())



"""## Resposta Q2

A consulta SQL foi desenvolvida utilizando DuckDB e reproduz a mesma lógica implementada em Python para cálculo do consumo aparente (ECA), cobertura (Co) e percentual de rateio (P). A utilização de funções analíticas (`SUM() OVER()`) permitiu calcular o percentual de rateio sem necessidade de subconsultas adicionais, tornando a consulta mais simples e eficiente.
"""

# Q3 — Previsão de consumo e geração

import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestRegressor


# -----------------------------
# Funções auxiliares
# -----------------------------

MES = "Geração Mensal Referência Month"
UC = "Unidade Consumidora (UC) Número de Instalação"
CONS = "Conta Consumo (kWh)"
GER = "Geração Mensal SUM Energia Gerada (kWh)"


def metricas(y_real, y_prev):
    y_real = np.asarray(y_real, dtype=float)
    y_prev = np.asarray(y_prev, dtype=float)

    mae = np.mean(np.abs(y_real - y_prev))

    # O MAPE não é adequado quando o valor real é zero.
    mascara = y_real != 0

    if mascara.any():
        mape = np.mean(
            np.abs(
                (y_real[mascara] - y_prev[mascara])
                / y_real[mascara]
            )
        ) * 100
    else:
        mape = np.nan

    wmape = (
        np.sum(np.abs(y_real - y_prev))
        / np.sum(np.abs(y_real))
        * 100
        if np.sum(np.abs(y_real)) > 0
        else np.nan
    )

    return mae, mape, wmape


def criar_features(df, alvo, grupo=None):
    if grupo:
        ordenacao = [grupo, MES]
    else:
        ordenacao = [MES]

    dados = df.sort_values(ordenacao).copy()

    if grupo:
        for lag in [1, 2, 3, 6, 12]:
            dados[f"lag_{lag}"] = (
                dados.groupby(grupo)[alvo].shift(lag)
            )

        dados["media_3m"] = (
            dados.groupby(grupo)[alvo]
            .transform(lambda x: x.shift(1).rolling(3).mean())
        )

        dados["media_6m"] = (
            dados.groupby(grupo)[alvo]
            .transform(lambda x: x.shift(1).rolling(6).mean())
        )

    else:
        for lag in [1, 2, 3, 6, 12]:
            dados[f"lag_{lag}"] = dados[alvo].shift(lag)

        dados["media_3m"] = (
            dados[alvo].shift(1).rolling(3).mean()
        )

        dados["media_6m"] = (
            dados[alvo].shift(1).rolling(6).mean()
        )

    dados["mes_numero"] = dados[MES].dt.month
    dados["mes_seno"] = np.sin(
        2 * np.pi * dados["mes_numero"] / 12
    )
    dados["mes_cosseno"] = np.cos(
        2 * np.pi * dados["mes_numero"] / 12
    )

    dados["tendencia"] = (
        dados[MES].dt.year * 12
        + dados[MES].dt.month
    )

    return dados


# ==========================================================
# Q3(a) — Consumo das Top 10 UCs
# ==========================================================

consumo_modelo = consumer_clean[
    [MES, UC, CONS]
].copy()

consumo_modelo[CONS] = pd.to_numeric(
    consumo_modelo[CONS],
    errors="coerce"
)

consumo_modelo = consumo_modelo.dropna(
    subset=[MES, UC, CONS]
)

# Consolidação de duplicidades estruturais UC + mês
consumo_modelo = (
    consumo_modelo
    .groupby([MES, UC], as_index=False)[CONS]
    .sum()
)

# Consumo negativo é considerado inválido para modelagem
consumo_modelo.loc[
    consumo_modelo[CONS] < 0,
    CONS
] = np.nan

# Top 10 UCs pelo consumo histórico
top_10 = (
    consumo_modelo
    .groupby(UC)[CONS]
    .sum(min_count=1)
    .nlargest(10)
    .index
    .tolist()
)

meses = pd.date_range(
    consumo_modelo[MES].min(),
    pd.Timestamp("2026-07-01"),
    freq="MS"
)

grade = pd.MultiIndex.from_product(
    [top_10, meses],
    names=[UC, MES]
).to_frame(index=False)

painel = grade.merge(
    consumo_modelo[
        consumo_modelo[UC].isin(top_10)
    ],
    on=[UC, MES],
    how="left"
)

painel = painel.sort_values([UC, MES])

# Interpolação apenas para modelagem
painel[CONS] = (
    painel.groupby(UC)[CONS]
    .transform(
        lambda x: x.interpolate(
            limit_direction="both"
        )
    )
)

# Julho é o mês que será previsto
painel.loc[
    painel[MES] == "2026-07-01",
    CONS
] = np.nan

features_consumo = criar_features(
    painel,
    CONS,
    grupo=UC
)

features_consumo = pd.get_dummies(
    features_consumo,
    columns=[UC],
    dtype=float
)

colunas_x = [
    coluna
    for coluna in features_consumo.columns
    if coluna not in [MES, CONS]
]

treino_consumo = features_consumo[
    features_consumo[MES] <= "2026-05-01"
].dropna(
    subset=colunas_x + [CONS]
)

validacao_consumo = features_consumo[
    features_consumo[MES] == "2026-06-01"
].dropna(
    subset=colunas_x + [CONS]
)

# Baseline: mesmo mês do ano anterior
prev_baseline_consumo = (
    validacao_consumo["lag_12"].to_numpy()
)

# Modelo avançado
modelo_consumo = RandomForestRegressor(
    n_estimators=400,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

modelo_consumo.fit(
    treino_consumo[colunas_x],
    treino_consumo[CONS]
)

prev_rf_consumo = modelo_consumo.predict(
    validacao_consumo[colunas_x]
)

metricas_baseline_consumo = metricas(
    validacao_consumo[CONS],
    prev_baseline_consumo
)

metricas_rf_consumo = metricas(
    validacao_consumo[CONS],
    prev_rf_consumo
)

# Escolha pelo menor MAE
treino_final_consumo = features_consumo[
    features_consumo[MES] <= "2026-06-01"
].dropna(
    subset=colunas_x + [CONS]
)

julho_consumo = features_consumo[
    features_consumo[MES] == "2026-07-01"
].dropna(
    subset=colunas_x
)

if (
    metricas_rf_consumo[0]
    <= metricas_baseline_consumo[0]
):
    modelo_consumo.fit(
        treino_final_consumo[colunas_x],
        treino_final_consumo[CONS]
    )

    previsao_julho_consumo = (
        modelo_consumo.predict(
            julho_consumo[colunas_x]
        )
    )

    modelo_vencedor_consumo = "Random Forest"

else:
    previsao_julho_consumo = (
        julho_consumo["lag_12"].to_numpy()
    )

    modelo_vencedor_consumo = (
        "Baseline sazonal de 12 meses"
    )


# Recuperar identificação das UCs
colunas_dummy_uc = [
    coluna
    for coluna in julho_consumo.columns
    if coluna.startswith(UC + "_")
]

lista_ucs = []

for _, linha in julho_consumo.iterrows():
    uc_encontrada = [
        coluna[len(UC) + 1:]
        for coluna in colunas_dummy_uc
        if linha[coluna] == 1
    ]

    lista_ucs.append(
        uc_encontrada[0]
        if uc_encontrada
        else ""
    )

previsoes_consumo = pd.DataFrame({
    "uc": lista_ucs,
    "previsao_consumo_jul_2026":
        previsao_julho_consumo
})

previsoes_consumo = (
    previsoes_consumo
    .sort_values(
        "previsao_consumo_jul_2026",
        ascending=False
    )
)


# ==========================================================
# Q3(b) — Geração da usina
# ==========================================================

geracao_modelo = power_clean[
    [MES, GER]
].copy()

geracao_modelo[GER] = pd.to_numeric(
    geracao_modelo[GER],
    errors="coerce"
)

geracao_modelo = (
    geracao_modelo
    .dropna()
    .groupby(MES, as_index=False)[GER]
    .sum()
    .sort_values(MES)
)

# O registro inicial de 1 kWh é tratado como
# período de comissionamento, não operação normal.
geracao_modelo = geracao_modelo[
    geracao_modelo[GER] > 1000
].copy()

geracao_modelo = pd.concat(
    [
        geracao_modelo,
        pd.DataFrame({
            MES: [pd.Timestamp("2026-07-01")],
            GER: [np.nan]
        })
    ],
    ignore_index=True
)

features_geracao = criar_features(
    geracao_modelo,
    GER
)

colunas_x_geracao = [
    coluna
    for coluna in features_geracao.columns
    if coluna not in [MES, GER]
]

treino_geracao = features_geracao[
    features_geracao[MES] <= "2026-05-01"
].dropna(
    subset=colunas_x_geracao + [GER]
)

validacao_geracao = features_geracao[
    features_geracao[MES] == "2026-06-01"
].dropna(
    subset=colunas_x_geracao + [GER]
)

prev_baseline_geracao = (
    validacao_geracao["lag_12"].to_numpy()
)

modelo_geracao = RandomForestRegressor(
    n_estimators=400,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

modelo_geracao.fit(
    treino_geracao[colunas_x_geracao],
    treino_geracao[GER]
)

prev_rf_geracao = modelo_geracao.predict(
    validacao_geracao[colunas_x_geracao]
)

metricas_baseline_geracao = metricas(
    validacao_geracao[GER],
    prev_baseline_geracao
)

metricas_rf_geracao = metricas(
    validacao_geracao[GER],
    prev_rf_geracao
)

treino_final_geracao = features_geracao[
    features_geracao[MES] <= "2026-06-01"
].dropna(
    subset=colunas_x_geracao + [GER]
)

julho_geracao = features_geracao[
    features_geracao[MES] == "2026-07-01"
].dropna(
    subset=colunas_x_geracao
)

if (
    metricas_rf_geracao[0]
    <= metricas_baseline_geracao[0]
):
    modelo_geracao.fit(
        treino_final_geracao[colunas_x_geracao],
        treino_final_geracao[GER]
    )

    previsao_geracao_julho = float(
        modelo_geracao.predict(
            julho_geracao[colunas_x_geracao]
        )[0]
    )

    modelo_vencedor_geracao = "Random Forest"

else:
    previsao_geracao_julho = float(
        julho_geracao["lag_12"].iloc[0]
    )

    modelo_vencedor_geracao = (
        "Baseline sazonal de 12 meses"
    )


# ==========================================================
# Resultado final
# ==========================================================

consumo_total_previsto = float(
    previsoes_consumo[
        "previsao_consumo_jul_2026"
    ].sum()
)

saldo_previsto = (
    previsao_geracao_julho
    - consumo_total_previsto
)

print("=== CONSUMO DAS TOP 10 UCs ===")

print(
    "Baseline - MAE, MAPE, WMAPE:",
    metricas_baseline_consumo
)

print(
    "Random Forest - MAE, MAPE, WMAPE:",
    metricas_rf_consumo
)

print(
    "Modelo escolhido:",
    modelo_vencedor_consumo
)

print(previsoes_consumo.to_string(index=False))

print("\n=== GERAÇÃO DA USINA ===")

print(
    "Baseline - MAE, MAPE, WMAPE:",
    metricas_baseline_geracao
)

print(
    "Random Forest - MAE, MAPE, WMAPE:",
    metricas_rf_geracao
)

print(
    "Modelo escolhido:",
    modelo_vencedor_geracao
)

print(
    "\nConsumo previsto das Top 10 UCs:",
    round(consumo_total_previsto, 2),
    "kWh"
)

print(
    "Geração prevista:",
    round(previsao_geracao_julho, 2),
    "kWh"
)

print(
    "Saldo previsto:",
    round(saldo_previsto, 2),
    "kWh"
)

if saldo_previsto >= 0:
    print(
        "Conclusão: a geração prevista cobre o "
        "consumo previsto das Top 10 UCs."
    )
else:
    print(
        "Conclusão: existe déficit de geração "
        "para as Top 10 UCs."
    )



KeyError: ...



"""## Interpretação da Q3

Foi utilizado como baseline o valor observado no mesmo mês do ano anterior, estratégia adequada para séries mensais com possível sazonalidade. Como modelo avançado, foi utilizado Random Forest com defasagens de 1, 2, 3, 6 e 12 meses, médias móveis, tendência temporal e mês do ano.

A seleção do modelo foi realizada com base no menor MAE na validação de junho/2026. O MAPE foi calculado apenas para observações reais diferentes de zero, porque essa métrica fica indefinida quando o consumo real é zero. Como alternativa mais robusta para a carteira, também foi apresentado o WMAPE.

Para a geração, o registro inicial de 1 kWh foi excluído da modelagem por representar provável período de comissionamento e não uma condição normal de operação.

A diferença entre a geração prevista e o consumo previsto indica se existe excedente ou déficit para julho/2026. Em caso de excedente, a Digital Grid pode ampliar a alocação ou captar novas UCs. Em caso de déficit, deve reduzir o compromisso de rateio, utilizar saldos existentes ou buscar geração complementar.
"""



# Q4 — REBALANCE simplificado

import pandas as pd
import numpy as np

MES = "Geração Mensal Referência Month"
UC = "Unidade Consumidora (UC) Número de Instalação"
CONS = "Conta Consumo (kWh)"
SALDO = "Conta Saldo Acumulado (kWh)"

# ---------------------------------------------------------
# 1. Preparação da base
# ---------------------------------------------------------

rebalance_base = consumer_clean[
    [MES, UC, CONS, SALDO]
].copy()

rebalance_base[MES] = pd.to_datetime(
    rebalance_base[MES],
    errors="coerce"
)

rebalance_base[CONS] = pd.to_numeric(
    rebalance_base[CONS],
    errors="coerce"
)

rebalance_base[SALDO] = pd.to_numeric(
    rebalance_base[SALDO],
    errors="coerce"
)

rebalance_base = rebalance_base.dropna(
    subset=[MES, UC]
)

# Consolida eventuais duplicidades de UC no mesmo mês
rebalance_base = (
    rebalance_base
    .groupby([MES, UC], as_index=False)
    .agg({
        CONS: "sum",
        SALDO: "max"
    })
)

# Consumos negativos não representam consumo operacional
rebalance_base.loc[
    rebalance_base[CONS] < 0,
    CONS
] = 0

ultimo_mes = rebalance_base[MES].max()

inicio_12m = (
    ultimo_mes - pd.DateOffset(months=11)
)

inicio_3m = (
    ultimo_mes - pd.DateOffset(months=2)
)

# ---------------------------------------------------------
# 2. Saldo atual de cada UC
# ---------------------------------------------------------

saldo_atual = (
    rebalance_base
    .sort_values(MES)
    .groupby(UC, as_index=False)
    .tail(1)[[UC, SALDO]]
    .rename(columns={SALDO: "saldo_antes"})
)

# ---------------------------------------------------------
# 3. Consumo médio e estabilidade nos últimos 12 meses
# ---------------------------------------------------------

historico_12m = rebalance_base[
    rebalance_base[MES].between(
        inicio_12m,
        ultimo_mes
    )
].copy()

estatisticas_12m = (
    historico_12m
    .groupby(UC)[CONS]
    .agg(
        consumo_medio_12m="mean",
        desvio_consumo_12m="std",
        meses_com_dados="count"
    )
    .reset_index()
)

estatisticas_12m[
    "desvio_consumo_12m"
] = estatisticas_12m[
    "desvio_consumo_12m"
].fillna(0)

estatisticas_12m["cv_consumo"] = np.where(
    estatisticas_12m["consumo_medio_12m"] > 0,
    estatisticas_12m["desvio_consumo_12m"]
    / estatisticas_12m["consumo_medio_12m"],
    np.inf
)

# ---------------------------------------------------------
# 4. Identificação das UCs inativas
# Critério: consumo total igual a zero nos últimos 3 meses
# ---------------------------------------------------------

consumo_3m = (
    rebalance_base[
        rebalance_base[MES].between(
            inicio_3m,
            ultimo_mes
        )
    ]
    .groupby(UC, as_index=False)[CONS]
    .sum()
    .rename(columns={
        CONS: "consumo_ultimos_3m"
    })
)

carteira = (
    saldo_atual
    .merge(
        estatisticas_12m,
        on=UC,
        how="left"
    )
    .merge(
        consumo_3m,
        on=UC,
        how="left"
    )
)

carteira["consumo_ultimos_3m"] = (
    carteira["consumo_ultimos_3m"]
    .fillna(0)
)

carteira["consumo_medio_12m"] = (
    carteira["consumo_medio_12m"]
    .fillna(0)
)

carteira["cv_consumo"] = (
    carteira["cv_consumo"]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(999)
)

carteira["status"] = np.where(
    carteira["consumo_ultimos_3m"] <= 0,
    "Inativa",
    "Ativa"
)

# Crédito preso nas UCs inativas
carteira["credito_recuperado"] = np.where(
    (carteira["status"] == "Inativa")
    & (carteira["saldo_antes"] > 0),
    carteira["saldo_antes"],
    0
)

credito_total_redistribuir = float(
    carteira["credito_recuperado"].sum()
)

# ---------------------------------------------------------
# 5. Teto obrigatório:
# saldo final máximo = 1 mês do consumo médio dos últimos 12 meses
# ---------------------------------------------------------

carteira["teto_saldo"] = (
    carteira["consumo_medio_12m"]
)

carteira["capacidade_receber"] = np.where(
    carteira["status"] == "Ativa",
    np.maximum(
        carteira["teto_saldo"]
        - carteira["saldo_antes"],
        0
    ),
    0
)

# ---------------------------------------------------------
# 6. Critério de priorização
# ---------------------------------------------------------
# Prioriza UCs com:
# - maior consumo médio;
# - menor volatilidade de consumo;
# - espaço disponível abaixo do teto.
#
# Quanto menor o coeficiente de variação, mais previsível a UC.

carteira["score_seguranca"] = np.where(
    carteira["capacidade_receber"] > 0,
    carteira["consumo_medio_12m"]
    / (1 + carteira["cv_consumo"]),
    0
)

# Caso existam previsões da Q3, usa a previsão como demanda esperada
if "previsoes_consumo" in globals():
    previsao_aux = previsoes_consumo.copy()

    previsao_aux["uc"] = (
        previsao_aux["uc"].astype(str)
    )

    carteira[UC] = carteira[UC].astype(str)

    carteira = carteira.merge(
        previsao_aux[
            [
                "uc",
                "previsao_consumo_jul_2026"
            ]
        ],
        left_on=UC,
        right_on="uc",
        how="left"
    )

    carteira[
        "demanda_prioridade"
    ] = carteira[
        "previsao_consumo_jul_2026"
    ].fillna(
        carteira["consumo_medio_12m"]
    )

    carteira["score_seguranca"] = np.where(
        carteira["capacidade_receber"] > 0,
        carteira["demanda_prioridade"]
        / (1 + carteira["cv_consumo"]),
        0
    )

# ---------------------------------------------------------
# 7. Função de redistribuição
# ---------------------------------------------------------

def redistribuir_credito(
    df,
    credito_disponivel
):
    resultado = df.copy()

    resultado["credito_recebido"] = 0.0

    # Ordena pela segurança:
    # maior score primeiro
    ordem = resultado.sort_values(
        [
            "score_seguranca",
            "capacidade_receber"
        ],
        ascending=[False, False]
    ).index

    restante = float(credito_disponivel)

    for indice in ordem:
        if restante <= 0:
            break

        capacidade = float(
            resultado.loc[
                indice,
                "capacidade_receber"
            ]
        )

        if capacidade <= 0:
            continue

        alocacao = min(
            capacidade,
            restante
        )

        resultado.loc[
            indice,
            "credito_recebido"
        ] = alocacao

        restante -= alocacao

    return resultado, restante


resultado_rebalance, credito_sobrante = (
    redistribuir_credito(
        carteira,
        credito_total_redistribuir
    )
)

# UCs inativas têm o crédito recuperado
resultado_rebalance["saldo_depois"] = np.where(
    resultado_rebalance["status"] == "Inativa",
    resultado_rebalance["saldo_antes"]
    - resultado_rebalance["credito_recuperado"],
    resultado_rebalance["saldo_antes"]
    + resultado_rebalance["credito_recebido"]
)

# Segurança numérica
resultado_rebalance["saldo_depois"] = (
    resultado_rebalance["saldo_depois"]
    .clip(lower=0)
)

# Validação da restrição
resultado_rebalance[
    "respeita_teto"
] = np.where(
    resultado_rebalance["status"] == "Ativa",
    resultado_rebalance["saldo_depois"]
    <= resultado_rebalance["teto_saldo"]
    + 1e-6,
    True
)

# ---------------------------------------------------------
# 8. Resultados
# ---------------------------------------------------------

colunas_resultado = [
    UC,
    "status",
    "consumo_medio_12m",
    "saldo_antes",
    "teto_saldo",
    "credito_recuperado",
    "credito_recebido",
    "saldo_depois",
    "respeita_teto"
]

df_rebalance = (
    resultado_rebalance[
        colunas_resultado
    ]
    .sort_values(
        [
            "credito_recebido",
            "credito_recuperado"
        ],
        ascending=False
    )
)

print("=== RESULTADO DO REBALANCE ===")

print(
    "Último mês disponível:",
    ultimo_mes.strftime("%Y-%m")
)

print(
    "UCs inativas:",
    (
        resultado_rebalance["status"]
        == "Inativa"
    ).sum()
)

print(
    "Crédito total recuperado:",
    round(
        credito_total_redistribuir,
        2
    ),
    "kWh"
)

print(
    "Crédito redistribuído:",
    round(
        credito_total_redistribuir
        - credito_sobrante,
        2
    ),
    "kWh"
)

print(
    "Crédito que não coube:",
    round(
        credito_sobrante,
        2
    ),
    "kWh"
)

print(
    "Todas as UCs respeitaram o teto?",
    resultado_rebalance[
        "respeita_teto"
    ].all()
)

display(df_rebalance)

# Q4 — REBALANCE simplificado e robusto

import pandas as pd
import numpy as np

mes_col = "Geração Mensal Referência Month"
uc_col = "Unidade Consumidora (UC) Número de Instalação"
consumo_col = "Conta Consumo (kWh)"
saldo_col = "Conta Saldo Acumulado (kWh)"

# Usa a base limpa; se ela não existir, usa a base original
base = (
    consumer_clean.copy()
    if "consumer_clean" in globals()
    else consumer.copy()
)

# Padronização
base[mes_col] = pd.to_datetime(base[mes_col], errors="coerce")
base[consumo_col] = pd.to_numeric(
    base[consumo_col], errors="coerce"
).fillna(0).clip(lower=0)

base[saldo_col] = pd.to_numeric(
    base[saldo_col], errors="coerce"
).fillna(0).clip(lower=0)

base = base.dropna(subset=[mes_col, uc_col])

# Consolidação de UC + mês
base = (
    base.groupby([mes_col, uc_col], as_index=False)
    .agg({
        consumo_col: "sum",
        saldo_col: "max"
    })
)

ultimo_mes = base[mes_col].max()
inicio_12m = ultimo_mes - pd.DateOffset(months=11)
inicio_3m = ultimo_mes - pd.DateOffset(months=2)

# Saldo mais recente de cada UC
saldo_atual = (
    base.sort_values(mes_col)
    .groupby(uc_col)
    .tail(1)
    [[uc_col, saldo_col]]
    .rename(columns={saldo_col: "saldo_antes"})
)

# Consumo médio mensal dos últimos 12 meses
# Divide por 12 para considerar meses sem consumo como zero
media_12m = (
    base[base[mes_col].between(inicio_12m, ultimo_mes)]
    .groupby(uc_col)[consumo_col]
    .sum()
    .div(12)
    .rename("consumo_medio_12m")
    .reset_index()
)

# Consumo nos últimos 3 meses
consumo_3m = (
    base[base[mes_col].between(inicio_3m, ultimo_mes)]
    .groupby(uc_col)[consumo_col]
    .sum()
    .rename("consumo_ultimos_3m")
    .reset_index()
)

carteira = (
    saldo_atual
    .merge(media_12m, on=uc_col, how="left")
    .merge(consumo_3m, on=uc_col, how="left")
    .fillna(0)
)

# UC inativa: nenhum consumo nos últimos 3 meses
carteira["status"] = np.where(
    carteira["consumo_ultimos_3m"] == 0,
    "Inativa",
    "Ativa"
)

# Crédito recuperado das UCs inativas
carteira["credito_recuperado"] = np.where(
    carteira["status"] == "Inativa",
    carteira["saldo_antes"],
    0
)

credito_disponivel = float(
    carteira["credito_recuperado"].sum()
)

# Teto: um mês de consumo médio
carteira["teto_saldo"] = carteira["consumo_medio_12m"]

# UCs acima do teto não recebem
carteira["capacidade_receber"] = np.where(
    carteira["status"] == "Ativa",
    np.maximum(
        carteira["teto_saldo"] - carteira["saldo_antes"],
        0
    ),
    0
)

# Prioridade: maior consumo médio e maior capacidade de absorção
carteira = carteira.sort_values(
    ["consumo_medio_12m", "capacidade_receber"],
    ascending=False
).reset_index(drop=True)

carteira["credito_recebido"] = 0.0
restante = credito_disponivel

for i in carteira.index:
    if restante <= 0:
        break

    capacidade = float(carteira.loc[i, "capacidade_receber"])

    if capacidade > 0:
        alocacao = min(capacidade, restante)
        carteira.loc[i, "credito_recebido"] = alocacao
        restante -= alocacao

# Saldo depois do REBALANCE
carteira["saldo_depois"] = np.where(
    carteira["status"] == "Inativa",
    carteira["saldo_antes"] - carteira["credito_recuperado"],
    carteira["saldo_antes"] + carteira["credito_recebido"]
)

# Verifica apenas as UCs que receberam créditos
carteira["recebimento_respeita_teto"] = np.where(
    carteira["credito_recebido"] > 0,
    carteira["saldo_depois"] <= carteira["teto_saldo"] + 0.000001,
    True
)

resultado_q4 = carteira[[
    uc_col,
    "status",
    "consumo_medio_12m",
    "saldo_antes",
    "teto_saldo",
    "credito_recuperado",
    "credito_recebido",
    "saldo_depois",
    "recebimento_respeita_teto"
]]

print("Último mês:", ultimo_mes.strftime("%Y-%m"))
print("UCs inativas:", (carteira["status"] == "Inativa").sum())
print("Crédito recuperado:", round(credito_disponivel, 2), "kWh")
print(
    "Crédito redistribuído:",
    round(credito_disponivel - restante, 2),
    "kWh"
)
print("Crédito que não coube:", round(restante, 2), "kWh")
print(
    "Todas as alocações respeitaram o teto:",
    carteira["recebimento_respeita_teto"].all()
)

display(resultado_q4)

from IPython.display import display as mostrar

mostrar(resultado_q4)

import pandas as pd
import numpy as np

print(type(pd))
print(type(np))

print(consumer_clean.head())

consumer.columns

print(power.columns.tolist())





"""### Correção da implementação da Q4

A implementação abaixo corresponde à versão final da solução, após ajustes realizados durante o desenvolvimento.

## Interpretação da Q4

Foram consideradas inativas as UCs sem consumo nos três meses mais recentes. O saldo existente nessas unidades foi classificado como crédito parado e recuperado para redistribuição.

A alocação priorizou UCs ativas com maior consumo médio nos últimos 12 meses, pois elas possuem maior capacidade de utilizar os créditos e menor risco de gerar nova vacância. A distribuição foi limitada ao espaço entre o saldo atual e o teto de um mês de consumo médio. UCs que já estavam acima desse teto não receberam novos créditos.

Caso reste crédito após a redistribuição, ele não deve ser alocado de forma forçada. A Digital Grid pode direcioná-lo para novas UCs com demanda comprovada, mantê-lo para o próximo ciclo ou revisar o volume de geração contratado.

# Q5 — Exploração e visão de negócio

## Qualidade dos dados

Durante a análise foram identificadas as seguintes anomalias:

- Registros duplicados, inclusive ocorrências da mesma UC no mesmo mês;
- Linha da base da usina sem data de referência;
- Valores negativos de consumo;
- Diferença entre as janelas temporais das bases de consumo e geração;
- Possíveis meses ausentes em algumas séries;
- Valores extremos que podem representar erro de medição ou situação operacional excepcional.

Em uma pipeline de produção, essas situações devem ser tratadas com validação de esquema, chave composta por UC e mês, padronização de datas, regras para valores negativos e nulos, detecção de outliers e registro das inconsistências em uma tabela de quarentena para auditoria. A pipeline também deve gerar alertas quando houver mudança brusca no volume de registros ou na distribuição dos dados.

## Ações de negócio

### Ação 1 — Alerta automático de crédito ocioso

Criar um alerta mensal para UCs cujo saldo acumulado ultrapasse um mês de consumo médio ou que permaneçam sem consumo por três meses consecutivos. Essas unidades devem entrar automaticamente na fila do REBALANCE para redistribuição do crédito.

### Ação 2 — Planejamento preditivo da carteira

Comparar mensalmente a geração prevista da usina com o consumo previsto das UCs. Em caso de excedente, priorizar a entrada de novas UCs ou aumentar a alocação para unidades com demanda estável. Em caso de déficit, reduzir novos compromissos de rateio e utilizar saldos existentes antes de contratar geração complementar.
"""



"""# Conclusão

A solução contemplou limpeza e validação dos dados, cálculo do rateio em Python e SQL, previsão de consumo e geração, simulação do REBALANCE e proposição de ações de negócio. O foco foi garantir consistência dos cálculos, reduzir crédito ocioso e apoiar decisões operacionais da Digital Grid.
"""